<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>moss_backend</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.66" />
    <PackageReference Include="FluentMigrator" Version="7.2.0" />
    <PackageReference Include="FluentMigrator.Runner" Version="7.2.0" />
    <PackageReference Include="FluentMigrator.Runner.Postgres" Version="7.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" Version="5.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="9.0.9" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="6.1.2" />
    <PackageReference Include="MongoDB.Driver" Version="3.5.0" />
    <PackageReference Include="Npgsql" Version="10.0.1" />
    <PackageReference Include="OPCFoundation.NetStandard.Opc.Ua" Version="1.5.377.21" />
    <PackageReference Include="Serilog.AspNetCore" Version="9.0.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
  </ItemGroup>

</Project>
